name: 'Build and Deploy to app engine'

on:
  push:
    branches:
      - '**'

env:
  PROJECT_ID: 'mimetic-retina-486715-i3' # TODO: update to your Google Cloud project ID
  REGION: 'us-central1' # TODO: update to your region
  SERVICE: 'test' # TODO: update to your service name
  WORKLOAD_IDENTITY_PROVIDER: 'projects/816163793182/locations/global/workloadIdentityPools/github-action/providers/github' # TODO: update to your workload identity provider
  SERVICE_ACCOUNT: "chatbot@mimetic-retina-486715-i3.iam.gserviceaccount.com"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate with GCP using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}"
          project_id: "${{ env.PROJECT_ID }}"

      # Install gcloud CLI
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build React app
      - name: Build React App
        run: npm run build

      # Deploy to App Engine
      - name: Deploy to App Engine
        run: |
          gcloud app deploy app.yaml --quiet
